#include "modules/register_module_types.h"

void initialize_relativity_engine_module(ModuleInitializationLevel p_level);
void uninitialize_relativity_engine_module(ModuleInitializationLevel p_level);
